services:
  appseed-app:
    container_name: appseed_app
    restart: always
    build: .
    networks:
      - db_network
      - web_network
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    container_name: nginx
    restart: always
    image: nginx:stable-alpine3.21-slim
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/staticfiles:ro
    networks:
      - web_network
    depends_on:
      - appseed-app

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  static_volume:
